version: "3.9"
version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: articlelate
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  server:
   image: server
   depends_on: 
       - postgres
   ports: 
       - "8080:8080"
   networks:
       - postgres-network


networks:
  postgres-network:
    driver: bridge