name: article-late-system-test

on:
  push:
    branches:
      - main

jobs:
  system-test:
    runs-on: ubuntu-latest
          
    steps:
    - name: Load project code
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
          java-version: '19'
          distribution: 'temurin'
      
    - name: Build and test server
      run:  cd /home/runner/work/ArticleLate/ArticleLate/server/restapi ; mvn package -Dmaven.test.skip=true

    - name: Create server-image
      run:  cd /home/runner/work/ArticleLate/ArticleLate/server/restapi/target ; mv restapi-0.0.1-SNAPSHOT.jar /home/runner/work/ArticleLate/ArticleLate/server ; cd /home/runner/work/ArticleLate/ArticleLate/server ; docker build -t server .
      
    - name: Run docker-compose.yml
      run:  cd /home/runner/work/ArticleLate/ArticleLate/server ; docker compose up -d --build

    - name: Run client
      run:  cd /home/runner/work/ArticleLate/ArticleLate/client ; npm install ; npm run start

    - name: Run e2e tests
      run:  cd /home/runner/work/ArticleLate/ArticleLate/client ; npx cypress run
      
