name: article-late-test

on: [push]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: articlelate
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
          java-version: '19'
          distribution: 'temurin'
          
    - name: Load project code
      uses: actions/checkout@v3
      
    - name: Create .env file
      run:  cd server/restapi ; echo -e "DB_URL=jdbc:postgresql://localhost:5432/articlelate\nUSER=postgres\nPASS=postgres" > .env
      
    - name: Build and test project
      run:  mvn package
      
